---
title: "CNprep"
author: "Alex Krasnitz, Guoli Sun"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CNprep}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>
**Package**: `r packageDescription("CNprep")[["Package"]]`<br />
**Authors**: `r packageDescription("CNprep")[["Author"]]`<br />
**Version**: `r packageDescription("CNprep")$Version`<br />
**Compiled date**: `r Sys.Date()`<br />
**License**: `r packageDescription("CNprep")[["License"]]`<br />

## License

The *CNprep* package and the underlying *CNprep* code 
are distributed under the [GPL-2 License](https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt). You are free to use and 
redistribute this software. 

## Citing


If you use this package for a publication, we would ask you to cite the 
following:

> Alex Krasnitz and Guoli Sun (2014). CNprep: Pre-process DNA Copy Number (CN) Data for Detection of CN Events. R package version 2.0. https://CRAN.R-project.org/package=CNprep


## Introduction

The *CNprep* package evaluates DNA copy number data, using both their initial 
form (copy number as a noisy function of genomic position) and their 
approximation by a piecewise-constant function (segmentation), for the purpose 
of identifying genomic regions where the copy number differs from the norm.
